### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by r4f4** [modularity-modules/sssd#1]
sssd includes the samba package. From its subpackages, the following issues arise:

* ctdb requires psmisc
* ctdb-tests requires nc

**Comment by r4f4** [comment]
Other samba subpackages issues:
package: 2:samba-pidl-4.6.4-1.module_4522ce56.noarch from repoclosure-Server.x86_64
  unresolved deps: 
     perl(Parse::Yapp)
     perl(Parse::Yapp::Driver)
package: 2:samba-vfs-cephfs-4.6.4-1.module_4522ce56.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     libcephfs.so.1()(64bit)
     libcephfs1
package: 2:samba-vfs-glusterfs-4.6.4-1.module_4522ce56.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     glusterfs >= 0:3.4.0.16
     glusterfs-api >= 0:3.4.0.16
     libgfapi.so.0()(64bit)
     libgfapi.so.0(GFAPI_3.4.0)(64bit)
     libgfapi.so.0(GFAPI_3.7.17)(64bit)

**Comment by r4f4** [comment]
package: check-0.11.0-2.module_4522ce56.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     libsubunit.so.0()(64bit)
package: check-devel-0.11.0-2.module_4522ce56.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     pkgconfig(libsubunit)

**Comment by r4f4** [comment]
firewalld includes the following subpackages and its deps:

package: firewall-applet-0.4.4.4-1.module_4522ce56.noarch from repoclosure-Server.x86_64
  unresolved deps: 
     dbus-x11
     libnotify
     python3-gobject
     python3-qt5
package: firewall-config-0.4.4.4-1.module_4522ce56.noarch from repoclosure-Server.x86_64
  unresolved deps: 
     dbus-x11
     gtk3
     python3-gobject

**Comment by r4f4** [comment]
package: nss_wrapper-1.1.3-2.module_4522ce56.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     cmake

**Comment by r4f4** [comment]
package: python-firewall-0.4.4.4-1.module_4522ce56.noarch from repoclosure-Server.x86_64
  unresolved deps: 
     python-decorator
     python-slip-dbus

**Comment by r4f4** [comment]
package: uid_wrapper-1.2.1-2.module_4522ce56.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     cmake

**Comment by phracek** [comment]
@r4f4 uid_wrapper needs cmake which is part of common-build-dependencies.
common-build-dependencies is part of requires.

Do you count with common-build-dependencies module?

**Comment by sgallagher** [comment]
@phracek @r4f4 Why is Samba included as API at all? SSSD requires a very small portion of samba to function. Specifically,
* `libsmbclient`
* `libwbclient`
* `samba-client-libs`

All of the other samba subpackages should be filtered out of the SSSD module. This will eliminate the repoclosure issue.

Similarly, there's no need for `firewall-applet` in the SSSD module; that's a GUI-only tool. And `check` is a build-time only tool; it should also be filtered out. I will send patches.

**Comment by sgallagher** [comment]
Actually, why is firewalld in this set at all? The `rationale` lists "A dependency of glusterfs", but this isn't the glusterfs module...

**Comment by phracek** [comment]
nss_wrapper is fixed by commit https://github.com/modularity-modules/sssd/commit/42b2773242cff1d2e0b6464e31c897b4969e4b5a http://pkgs.fedoraproject.org/cgit/modules/sssd.git/commit/?h=f26&id=b0f1422e9e7fe9f0a8a3b181f4c654843d4e341a

**Comment by r4f4** [comment]
The only thing I see left is that it includes `quota` which is already part of shared-userspace.

**Comment by phracek** [comment]
@r4f4 quota is fixed by commit https://github.com/modularity-modules/sssd/commit/2fd67a9d55439181ab0a23e22e9531a55096de3a. In Fedora Modules by dist-git commit http://pkgs.fedoraproject.org/cgit/modules/sssd.git/commit/?h=f26&id=3b00eca2425a2384141516a197247cf6575801ff

mbs-build id: https://mbs.fedoraproject.org/module-build-service/1/module-builds/704

Please close it if it is fixed.

**Comment by r4f4** [comment]
It's all good now. Thanks.
