### ISSUE TITLE
module install sssd fails

### ISSUE THREAD

**Issue by alexxa** [modularity-modules/sssd#4]
@KarstenHopp 

------------------------------- DNF ----------------------------------
Installed Packages
dnf.noarch          2.7.3-1.module_e1d44a88.modularity.1.3fb9e5c       @anaconda
libdnf.x86_64       0.10.1-2.module_e1d44a88.modularity.1              @anaconda
----------------------------------------------------------------------
Image built with (KOJI composes):
		GIT:      	https://github.com/container-images/boltron-27
		Base:     	Fedora-Modular-Bikeshed-20171011.n.0
Image running aginst (KOJI Composes):
		Bike: 	Fedora-Modular-Bikeshed-20171012.n.0
Last metadata expiration check: 0:02:30 ago on Fri 13 Oct 2017 12:42:27 PM UTC.
Fedora - Bikeshed - Developmental packages for the next Fedora release

(item=sssd) =>  
Problem 1: conflicting requests  - nothing provides libtalloc.so.2()(64bit) needed by python2-sss-1.15.3-3.module_5bb98feb.x86_64

Problem 2: conflicting requests  - nothing provides libtalloc.so.2()(64bit) needed by sssd-dbus-1.15.3-3.module_5bb98feb.x86_64

Problem 3: conflicting requests  - nothing provides libtalloc.so.2()(64bit) needed by sssd-common-pac-1.15.3-3.module_5bb98feb.x86_64

Problem 4: conflicting requests  - nothing provides libtalloc.so.2()(64bit) needed by sssd-krb5-1.15.3-3.module_5bb98feb.x86_64

Problem 5: conflicting requests  - nothing provides libtalloc.so.2()(64bit) needed by sssd-krb5-common-1.15.3-3.module_5bb98feb.x86_64

Problem 6: conflicting requests  - nothing provides libtalloc.so.2()(64bit) needed by sssd-ad-1.15.3-3.module_5bb98feb.x86_64

Problem 7: conflicting requests  - nothing provides libtalloc.so.2()(64bit) needed by sssd-ldap-1.15.3-3.module_5bb98feb.x86_64

Problem 8: conflicting requests  - nothing provides libtalloc.so.2()(64bit) needed by libsss_certmap-1.15.3-3.module_5bb98feb.x86_64

Problem 9: conflicting requests  - nothing provides libtalloc.so.2()(64bit) needed by sssd-ipa-1.15.3-3.module_5bb98feb.x86_64

Problem 10: conflicting requests  - nothing provides libtalloc.so.2()(64bit) needed by sssd-common-1.15.3-3.module_5bb98feb.x86_64

Problem 11: package sssd-1.15.3-3.module_5bb98feb.x86_64 requires sssd-ldap = 1.15.3-3.module_5bb98feb, but none of the providers can be installed  - conflicting requests  - nothing provides libtalloc.so.2()(64bit) needed by sssd-ldap-1.15.3-3.module_5bb98feb.x86_64

**Comment by nphilipp** [comment]
libtalloc etc. should eventually be picked up by platform: https://github.com/fedora-modularity/hp/issues/25
